// <auto-generated />
using System;
using Bygaard.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Bygaard.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Bygaard.Entities.GrowRoom", b =>
                {
                    b.Property<Guid>("GrowRoomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumberOfTrolleys")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("GrowRoomId");

                    b.ToTable("GrowRooms");

                    b.HasData(
                        new
                        {
                            GrowRoomId = new Guid("a2aa3bda-3255-4ff6-937f-579d71850a0a"),
                            CreatedAt = new DateTime(2023, 2, 17, 13, 7, 1, 375, DateTimeKind.Local).AddTicks(5697),
                            Name = "1",
                            NumberOfTrolleys = 16,
                            UpdatedAt = new DateTime(2023, 2, 17, 13, 7, 1, 377, DateTimeKind.Local).AddTicks(7332)
                        },
                        new
                        {
                            GrowRoomId = new Guid("542d024c-651b-4642-a7d6-433dd2584684"),
                            CreatedAt = new DateTime(2023, 2, 17, 13, 7, 1, 377, DateTimeKind.Local).AddTicks(7691),
                            Name = "2",
                            NumberOfTrolleys = 16,
                            UpdatedAt = new DateTime(2023, 2, 17, 13, 7, 1, 377, DateTimeKind.Local).AddTicks(7701)
                        },
                        new
                        {
                            GrowRoomId = new Guid("613cf80c-75bd-45af-ad33-87ab6c66c07f"),
                            CreatedAt = new DateTime(2023, 2, 17, 13, 7, 1, 377, DateTimeKind.Local).AddTicks(7704),
                            Name = "3",
                            NumberOfTrolleys = 16,
                            UpdatedAt = new DateTime(2023, 2, 17, 13, 7, 1, 377, DateTimeKind.Local).AddTicks(7707)
                        },
                        new
                        {
                            GrowRoomId = new Guid("ddb0750f-a819-430a-9da5-73c36711c7ac"),
                            CreatedAt = new DateTime(2023, 2, 17, 13, 7, 1, 377, DateTimeKind.Local).AddTicks(7710),
                            Name = "4",
                            NumberOfTrolleys = 16,
                            UpdatedAt = new DateTime(2023, 2, 17, 13, 7, 1, 377, DateTimeKind.Local).AddTicks(7711)
                        },
                        new
                        {
                            GrowRoomId = new Guid("41ed5331-e32e-4ff4-97f7-f5a6376320f0"),
                            CreatedAt = new DateTime(2023, 2, 17, 13, 7, 1, 377, DateTimeKind.Local).AddTicks(7714),
                            Name = "5",
                            NumberOfTrolleys = 16,
                            UpdatedAt = new DateTime(2023, 2, 17, 13, 7, 1, 377, DateTimeKind.Local).AddTicks(7716)
                        },
                        new
                        {
                            GrowRoomId = new Guid("b1914f96-425e-4f73-83b7-1d44e0b4b552"),
                            CreatedAt = new DateTime(2023, 2, 17, 13, 7, 1, 377, DateTimeKind.Local).AddTicks(7718),
                            Name = "6",
                            NumberOfTrolleys = 16,
                            UpdatedAt = new DateTime(2023, 2, 17, 13, 7, 1, 377, DateTimeKind.Local).AddTicks(7720)
                        });
                });

            modelBuilder.Entity("Bygaard.Entities.Stock", b =>
                {
                    b.Property<Guid>("StockId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StockId");

                    b.ToTable("Stock");

                    b.HasData(
                        new
                        {
                            StockId = new Guid("55ff02c4-50b4-483c-8594-84b2996b667e"),
                            Name = "Main Storage"
                        });
                });

            modelBuilder.Entity("Bygaard.Entities.Substrate", b =>
                {
                    b.Property<Guid>("SubstrateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DaysInGrowthPhase")
                        .HasColumnType("int");

                    b.Property<int>("DaysInHarvestingPhase")
                        .HasColumnType("int");

                    b.Property<int>("DaysInOpeningPhase1")
                        .HasColumnType("int");

                    b.Property<int>("DaysInOpeningPhase2")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<double>("KgsInStock")
                        .HasColumnType("float");

                    b.Property<string>("LatinName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("StockId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("SubstrateId");

                    b.HasIndex("StockId");

                    b.ToTable("Substrates");
                });

            modelBuilder.Entity("Bygaard.Entities.Substrate", b =>
                {
                    b.HasOne("Bygaard.Entities.Stock", "Stock")
                        .WithMany("Substrates")
                        .HasForeignKey("StockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Stock");
                });

            modelBuilder.Entity("Bygaard.Entities.Stock", b =>
                {
                    b.Navigation("Substrates");
                });
#pragma warning restore 612, 618
        }
    }
}
