// <auto-generated />
using System;
using Bygaard.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Bygaard.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Bygaard.Entities.Batch", b =>
                {
                    b.Property<Guid>("BatchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<double>("KilosOfProduce")
                        .HasColumnType("float");

                    b.Property<double>("KilosOfSubstrate")
                        .HasColumnType("float");

                    b.Property<string>("Substrate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("BatchId");

                    b.ToTable("Batches");
                });

            modelBuilder.Entity("Bygaard.Entities.GrowRoom", b =>
                {
                    b.Property<Guid>("GrowRoomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumberOfTrolleys")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("GrowRoomId");

                    b.ToTable("GrowRooms");

                    b.HasData(
                        new
                        {
                            GrowRoomId = new Guid("6c61beff-21d2-4048-81da-dd726c3257d9"),
                            CreatedAt = new DateTime(2023, 5, 23, 15, 52, 21, 425, DateTimeKind.Local).AddTicks(1144),
                            Name = "1",
                            NumberOfTrolleys = 16,
                            UpdatedAt = new DateTime(2023, 5, 23, 15, 52, 21, 426, DateTimeKind.Local).AddTicks(8153)
                        },
                        new
                        {
                            GrowRoomId = new Guid("77e75f7f-2da2-48dc-b260-f7b9a8e625d5"),
                            CreatedAt = new DateTime(2023, 5, 23, 15, 52, 21, 426, DateTimeKind.Local).AddTicks(8487),
                            Name = "2",
                            NumberOfTrolleys = 16,
                            UpdatedAt = new DateTime(2023, 5, 23, 15, 52, 21, 426, DateTimeKind.Local).AddTicks(8497)
                        },
                        new
                        {
                            GrowRoomId = new Guid("33f0de00-3dec-4e20-abdc-843e37decadc"),
                            CreatedAt = new DateTime(2023, 5, 23, 15, 52, 21, 426, DateTimeKind.Local).AddTicks(8501),
                            Name = "3",
                            NumberOfTrolleys = 16,
                            UpdatedAt = new DateTime(2023, 5, 23, 15, 52, 21, 426, DateTimeKind.Local).AddTicks(8503)
                        },
                        new
                        {
                            GrowRoomId = new Guid("e91b5480-563c-490c-babc-51de101e9be8"),
                            CreatedAt = new DateTime(2023, 5, 23, 15, 52, 21, 426, DateTimeKind.Local).AddTicks(8506),
                            Name = "4",
                            NumberOfTrolleys = 16,
                            UpdatedAt = new DateTime(2023, 5, 23, 15, 52, 21, 426, DateTimeKind.Local).AddTicks(8508)
                        },
                        new
                        {
                            GrowRoomId = new Guid("f9359442-730d-40c9-9ec5-27a46686992a"),
                            CreatedAt = new DateTime(2023, 5, 23, 15, 52, 21, 426, DateTimeKind.Local).AddTicks(8511),
                            Name = "5",
                            NumberOfTrolleys = 16,
                            UpdatedAt = new DateTime(2023, 5, 23, 15, 52, 21, 426, DateTimeKind.Local).AddTicks(8513)
                        },
                        new
                        {
                            GrowRoomId = new Guid("53047329-2afe-4d78-a3e1-acbdaf1fbb9a"),
                            CreatedAt = new DateTime(2023, 5, 23, 15, 52, 21, 426, DateTimeKind.Local).AddTicks(8515),
                            Name = "6",
                            NumberOfTrolleys = 16,
                            UpdatedAt = new DateTime(2023, 5, 23, 15, 52, 21, 426, DateTimeKind.Local).AddTicks(8517)
                        });
                });

            modelBuilder.Entity("Bygaard.Entities.StockItem", b =>
                {
                    b.Property<Guid>("StockItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<double>("KilosOfProduce")
                        .HasColumnType("float");

                    b.Property<string>("SubstrateName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("StockItemId");

                    b.ToTable("StockItems");
                });

            modelBuilder.Entity("Bygaard.Entities.Substrate", b =>
                {
                    b.Property<Guid>("SubstrateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DaysToGrow")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LatinName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("SubstrateId");

                    b.ToTable("Substrates");
                });
#pragma warning restore 612, 618
        }
    }
}
